---
- name: Install CLI Apps
  package:
    name:
      - ansible
      - bat
      - curl
      - fd-find
      - htop
      - httpie
      - jq
      - lftp
      - mmv
      - p7zip-full
      - p7zip-rar
      - parallel
      - prettyping
      - progress
      - ripgrep
      - sshuttle
      - tree
      - yamllint
    state: present
  become: true

- name: Install some more dependencies
  npm:
    name: fx
    state: latest
    global: true
  become: true
