---
- name: Install fish with homebrew  # noqa package-latest
  homebrew:
    name:
      - fish
      - git
      - direnv
    state: latest

- name: Configure fish
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
  with_items:
    - {src: homebrew.fish, dest: ~/.config/fish/conf.d/homebrew.fish}

- name: Install some Oh-My-Fish plugins  # noqa command-instead-of-shell
  shell: omf install "{{ item }}"
  args:
    executable: fish
    creates: "~/.local/share/omf/pkg/{{ item | urlsplit('path') | basename | splitext | first }}"
  with_items:
    - brew
    - https://github.com/thegcat/caffeinate.git
