- name: Install fish and dependencies
  include: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: Get Oh-My-Fish
  git:
    repo: https://github.com/oh-my-fish/oh-my-fish
    dest: ~/Code/thegcat/oh-my-fish
    depth: 1
  register: omf_git

- name: Install Oh-My-Fish
  command: ~/Code/thegcat/oh-my-fish/bin/install --offline --noninteractive
  when: omf_git.changed

- name: Configure fish
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: config.fish, dest: ~/.config/fish/config.fish }
    - { src: functions_fish_user_key_bindings.fish, dest: ~/.config/fish/functions/fish_user_key_bindings.fish }
