- name: Collection Facts
  hosts: local
  gather_facts: yes

- name: Setup dotfiles and environment
  hosts: local
  roles:
    - { role: package_manager, tags: ['bootstrap'] }
    - fish
    - vim
    - macos
    - ssh
    - terminal
    - git
    - ruby
    - fsinfo
