---
- name: Collection Facts
  hosts: local
  gather_facts: true

- name: Setup dotfiles and environment
  hosts: local
  roles:
    - {role: package_manager, tags: ['bootstrap']}
    - terminal
    - fish
    - vim
    - system_base
    - ssh
    - git
    - ruby
    - fsinfo
    - planio
