---
- name: Add fsinfo ssh config
  copy:
    dest: ~/.ssh/conf.d/fsinfo.conf
    content: |
      Host fsi-jump
        User root
        Hostname sshjump.oh14.de
        Port 22222

      Host octopussy
        Hostname fsinfo-alt.cs.tu-dortmund.de
        User root
        LocalForward 8302 octopussy.cs.tu-dortmund.de:389

      Host irb
        Hostname plutonium.cs.tu-dortmund.de
        User schaef00
