---
- name: Create ssh key-pair for thegcat
  user:
    name: thegcat
    createhome: false
    generate_ssh_key: true
    ssh_key_type: ed25519

- name: Add default config
  copy:
    dest: ~/.ssh/config
    content: |
      Host *
      Compression yes

      Include conf.d/*
    mode: 0644
