- name: Create ssh key-pair for thegcat
  user:
    name: thegcat
    createhome: no
    generate_ssh_key: yes
    ssh_key_type: ed25519

- name: Add default config
  copy:
    dest: ~/.ssh/config
    content: |
      Host *
      Compression yes

      Include conf.d/*
