- name: Create ssh key-pair for thegcat
  user:
    name: thegcat
    createhome: no
    generate_ssh_key: yes
    ssh_key_bits: 4096

- name: Make sure the ssh config file is present
  file:
    path: ~/.ssh/config
    state: touch

- name: Insert default config
  blockinfile:
    path: ~/.ssh/config
    marker: "# {mark} ANSIBLE MANAGED BLOCK base"
    block: |
      Host *
      Compression yes
