# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="blinks"

# Uncomment the following line to disable command auto-correction.
DISABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(brew brew-cask bundler chpwd_profiles gem git knife osx rails sudo tmux)

source $ZSH/oh-my-zsh.sh

# User configuration

export PATH="/usr/local/bin:$PATH" # Add hombrew
export PATH="$PATH:$HOME/.rvm/bin" # Add RVM

zstyle ':chpwd:profiles:*' re-execute false
zstyle ":chpwd:profiles:$HOME/Code/planio(|/|/*)" profile planio
chpwd_profiles

chpwd_profile_planio()
{
  print "Switching to profile: $profile"

  export GIT_AUTOR_EMAIL='felix@plan.io'
  export GIT_COMMITTER_EMAIL='felix@plan.io'
}

chpwd_leave_profile_planio()
{
  print "Leaving profile: $CHPWD_PROFILE"

  unset GIT_AUTOR_EMAIL
  unset GIT_COMMITTER_EMAIL
}
