---
- name: Install git
  homebrew:
    name:
      - git
      - git-delta
    state: latest

- name: Configure git (macOS specific)
  git_config:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    scope: global
  with_items:
    - {key: credential.helper, value: osxkeychain}  # use macOS keychain to store credentials
