runtime bundle/vim-pathogen/autoload/pathogen.vim
execute pathogen#infect()

" map leader to comma
let mapleader = ","

" Use syntax-highlighting
syntax on

" Do smart stuff based on filetype
filetype plugin indent on

" Show command being executed
set showcmd

" Don't wrap lines
set nowrap

" Line numbers
set number relativenumber

" Whitespace
set tabstop=2 shiftwidth=2 expandtab

" Search
set ignorecase
set smartcase

" Where am I? (show only on current window not in insert mode)
autocmd InsertLeave,WinEnter * set cursorline
autocmd InsertEnter,WinLeave * set nocursorline

" 120 columns
set colorcolumn=120

" UTF-8 encoding by default
set encoding=utf8

" Show indent guides
let g:indent_guides_enable_on_vim_startup = 1

" See http://flaviusim.com/blog/resizing-vim-window-splits-like-a-boss/ for
" more information about the next 2 sections
" Windows with at least 5 lines, active Window with 30 lines
set winheight=30
set winminheight=5

" Resize windows by more useful amounts
nnoremap <silent> + :exe "resize " . (winheight(0) * 3/2)<CR>
nnoremap <silent> - :exe "resize " . (winheight(0) * 2/3)<CR>

" Powerline
python3 from powerline.vim import setup as powerline_setup
python3 powerline_setup()
python3 del powerline_setup
" Let powerline do mode-showing things
set noshowmode

" Theme
let base16colorspace=256
colorscheme base16-tomorrow-night

" Copy to/from the system clipboard
set clipboard+=unnamed

" Don't mix fugitive and editorconfig
" https://github.com/editorconfig/editorconfig-vim#recommended-options
let g:EditorConfig_exclude_patterns = ['fugitive://.*', 'scp://.*']

" better whitespace
let g:strip_whitespace_on_save = 1
let g:strip_whitelines_at_eof=1

" CtrlP
let g:ctrlp_clear_cache_on_exit = 0
let g:ctrlp_follow_symlinks = 1
let g:ctrlp_custom_ignore = {
  \ 'dir': '\v[\/]\.(git|hg|svn)$',
  \ 'file': '\v\.(git|pyc|whl)$',
  \ }

" ale
let g:ale_sign_warning=''
let g:ale_sign_error=''
hi ALEErrorSign ctermfg=9 ctermbg=18
nmap <silent> <C-n> <Plug>(ale_previous_wrap)
nmap <silent> <C-m> <Plug>(ale_next_wrap)

" Set 78 char width for textfiles
autocmd FileType text setlocal textwidth=78
autocmd FileType plaintex setlocal textwidth=78
autocmd FileType markdown setlocal textwidth=78
autocmd FileType xml setlocal textwidth=78

" use ripgrep in ack.vim
if executable('rg')
  let g:ackprg = 'rg --vimgrep --smart-case'
endif
" don't jump to the first result
cnoreabbrev Ack Ack!
nnoremap <Leader>a :Ack!<Space>

" ignore certain file types in searches
set wildignore+=*.so,*.swp,*.zip,*.log,*.aux,*~,.DS_Store,*.pyg,*.o
