---
- name: Install iTerm2
  homebrew_cask:
    name:
      - iterm2
    state: upgraded

- name: Install terminal dependencies  # noqa package-latest
  homebrew:
    name:
      - tmux
      - reattach-to-user-namespace
      - python
    state: latest

- name: Install iTerm2 Tomorrow Night theme  # noqa no-handler
  command: open '~/Code/thegcat/base16-iterm2/itermcolors/base16-tomorrow-night.itermcolors'
  when: tomorrow_git.results[0].changed
