---
- name: Get Tomorrow themes
  git:
    repo: https://github.com/{{ item.repo }}.git
    dest: "{{ item.dest }}"
    depth: 1
  register: tomorrow_git
  with_items:
    - {repo: martinlindhe/base16-iterm2, dest: ~/Code/thegcat/base16-iterm2}
    - {repo: chriskempson/base16-shell, dest: ~/.config/base16-shell}

- name: Instal terminal dependencies
  include: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: Install Powerline
  pip:
    name: git+https://github.com/powerline/powerline.git@2.8.2
    executable: pip3

- name: Get Powerline install directory
  shell: "pip3 show powerline-status | awk '/^Location: / {print $2}'"
  check_mode: false
  register: powerline_location

- name: Set Powerline install directory fact
  set_fact:
    powerline_dir: "{{ powerline_location.stdout }}"

- name: Make sure needed directories are present
  file:
    path: ~/.config/powerline/themes/tmux
    state: directory

- name: Configure tmux with powerline and fish and tpm
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - {src: tmux.conf.j2, dest: ~/.tmux.conf}

- name: Configure tmux with powerline and fish and tpm
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - {src: powerline_themes_tmux_default.json, dest: ~/.config/powerline/themes/tmux/default.json}
    - {src: powerline_themes_shell_default.json, dest: ~/.config/powerline/themes/shell/default.json}
    - {src: powerline_colorschemes_default.json, dest: ~/.config/powerline/colorschemes/default.json}
    - {src: powerline_colors.json, dest: ~/.config/powerline/colors.json}
