---
- name: Install vim and dependencies  # noqa package-latest
  package:
    name:
      - vim
      - npm
    state: latest
  become: true

- name: Install some more dependencies  # noqa package-latest
  npm:
    name: markdownlint-cli
    state: latest
    global: true
  become: true
