---
- name: Install vim and dependencies
  package:
    name:
      - vim
    state: latest
  become: yes

- name: Install some more dependencies
  npm:
    name: markdownlint-cli
    state: latest
    global: true
