- name: Install ruby dependencies
  include: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: Install some Oh-My-Fish plugins
  shell: omf install "{{ item }}"
  args:
    executable: "{{ fish_executable.stdout }}"
  with_items:
    - bundler
    - gem
    - rbenv

- name: install a sensible .gemrc
  copy:
    dest: ~/.gemrc
    content: |
      gem: --no-document --no-ri --no-rdoc

- name: install a sensible bundle config
  copy:
    dest: ~/.bundle/config
    content: |
      ---
      BUNDLE_JOBS: "8"

- name: set some defaults for rbenv installation
  copy:
    dest: ~/.config/fish/conf.d/ruby-build.fish
    content: |
      set -agx RUBY_CONFIGURE_OPTS --disable-install-doc
