---
- name: Install ruby dependencies
  include: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: Install some Oh-My-Fish plugins  # noqa command-instead-of-shell
  shell: omf install "{{ item }}"
  args:
    executable: "{{ fish_executable.stdout }}"
    creates: "~/.local/share/omf/pkg/{{ item }}"
  with_items:
    - bundler
    - gem
    - rbenv

- name: install a sensible .gemrc
  copy:
    dest: ~/.gemrc
    content: |
      gem: --no-document --no-ri --no-rdoc
    mode: 0644

- name: install a sensible bundle config
  copy:
    dest: ~/.bundle/config
    content: |
      ---
      BUNDLE_JOBS: "8"
      BUNDLE_BUILD__LIBV8: "--with-system-v8 --with-v8-dir=/opt/homebrew/opt/v8@3.15/"
      BUNDLE_BUILD__THERUBYRACER: "--with-system-v8 --with-v8-dir=/opt/homebrew/opt/v8@3.15/"
      BUNDLE_BUILD__SQLITE3: "--with-sqlite3-dir=/opt/homebrew/opt/sqlite"
      BUNDLE_BUILD__FFI: "--enable-libffi-alloc"
      BUNDLE_BUILD__MYSQL2: "--with-mysql-dir=/opt/homebrew/opt/mysql@5.7 --with-mysql-lib=/opt/homebrew/opt/mysql@5.7/lib --with-mysql-config=/opt/homebrew/opt/mysql@5.7/bin/mysql_config --with-mysql-include=/opt/homebrew/opt/mysql@5.7/include/mysql"
      BUNDLE_BUILD__LOCAL___FASTIMAGE_RESIZE: "--with-opt-dir=/opt/homebrew/opt/gd"
    mode: 0644

- name: set some defaults for rbenv installation
  copy:
    dest: ~/.config/fish/conf.d/ruby-build.fish
    content: |
      set -agx RUBY_CONFIGURE_OPTS --disable-install-doc
    mode: 0644
